##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

model:
  horizon: 1
  state_filter_cfg:
    filter_coeff:
      position: 1.0
      velocity: 1.0
      acceleration: 0.0
    enable: False
  dt_traj_params:
    base_dt: 0.02
    base_ratio: 1.0
    max_dt: 0.25
  vel_scale: 1.0
  control_space: 'POSITION'
  teleport_mode: True

cost:
  grasp_cfg:
    weight: [100, 1000, 10] # grasp loss, dist loss, regu loss
    perturb_strength_bound: [0.01, 0.02]
  cspace_cfg:
    weight: 0.0
  bound_cfg:
    weight: 100.0
    activation_distance: [0.1]
    null_space_weight: [0.0]
  primitive_collision_cfg:
    weight: 100.0
    use_sweep: False
    classify: False
    activation_distance: 0.01
  self_collision_cfg:
    weight: 100.0
    classify: False
    activation_distance: 0.002
  joint_consistency_cfg:
    weight: 0
    group_allowed_diff: [0.01,0.1]
    group_weight: [2.0, 1.0]
    selected_joint_groups:
     - ['rh_FFJ3', 'rh_MFJ3', 'rh_RFJ3', 'rh_LFJ3']
     - ['rh_FFJ4', 'rh_MFJ4', 'rh_RFJ4', 'rh_LFJ4']  # 指末端

lbfgs:
  n_iters: 500      # iterations in optimization
  inner_iters: 50
  lr_decay_rate: 0.95
  cold_start_n_iters: null
  min_iters: 20
  line_search_scale:  [0.1] # search step for each base_scale. If use [0.01, 0.1], the optimization will be easily stucked in the local minima!
  base_scale: [0.01, 0.1, 0.1]  # learning rate for translation, rotation, and qpose
  retain_best: False
  momentum: True
  normalize_grad: True
  fixed_iters: True
  cost_convergence: 1e-7
  cost_delta_threshold: 1e-6 #0.0001
  cost_relative_threshold: 1.0
  epsilon: 0.01 #0.01 # used only in stable_mode
  history: 6
  horizon: 1
  use_cuda_graph: True
  n_problems: 1
  store_debug: False
  use_cuda_kernel: True
  stable_mode: True
  line_search_type: "greedy" 
  use_cuda_line_search_kernel: True
  use_cuda_update_best_kernel: True
  sync_cuda_time: True
  step_scale: 1.0 
  use_coo_sparse: True
  last_best: 10
  debug_info:
    visual_traj       : null #'ee_pos_seq'
  