world:
  indicator: '{$OBJECT_CODE}'
  template_path: "object/DGN_obj/processed_data/{$OBJECT_CODE}/mesh/simplified.obj"
  additional_cfg_path: 
  selection:
    id_lst_path: object/DGN_obj/valid_split/hook.json
    id:    
    start: 0
    end: 100
    repeat: 4
    shuffle: True 
  base_info_path: object/DGN_obj/processed_data/{$OBJECT_CODE}/info/simplified.json
  urdf_path: object/DGN_obj/processed_data/{$OBJECT_CODE}/urdf/coacd.urdf
  fixed_scale_lst: [0.2, 0.2, 0.2, 0.2]
  fixed_pose_lst: [[0.0, 0.0, 0.0, 1, 0, 0, 0.0]]
  # pose_path: object/DGN_obj/processed_data/{$OBJECT_CODE}/info/tabletop_pose.json



robot_file: "right_shadow_hook.yml"

robot_file_with_arm: "ur10e_shadow_sim.yml"
base_cfg_file: "base_grasp_joint_cons.yml"
particle_file: "particle_grasp_debug.yml"
gradient_file: "gradient_grasp_joint.yml"

exp_name: 'debug'
seed_num: 8
seeder_cfg:
  obj_sample:
    num: 128
    inflate: 0.1
    convex_hull: True
    collision_free: True 
  ik_init_q:
  load_path: 
  skip_transfer: False
  t:  
  r:  
  q: [ 0, 1.2, 0, -0.2, 0, -0.1, 0.3, 0., 0., 0, 0.3, 0., 0., -0.1, 0.3, 0., 0., 0, -0.2, 0.3, 0., 0.] # qpose: TH, FF, MF, RF, LF
  jitter_angle: [[-180, -15, -15], [180, 15, 15]]
  jitter_dist: [[0.0, -0.03, -0.03], [0.03, 0.03, 0.03]]

grasp_contact_strategy:
  contact_points_name:
     ['rh_thdistal/1',  # 拇指远端，抵住杯把
     'rh_ffmiddle/0', 'rh_ffdistal/1',  # 食指
     'rh_mfmiddle/0', 'rh_mfdistal/1',  # 中指
     'rh_rfmiddle/0', 'rh_rfdistal/2','rh_lfproximal/0','rh_lfdistal/2']  # 无名指

  opt_progress: [0.0, 0.6, 0.8]
  distance: [0.01, 0.01, 0.0]
  contact_query_mode: [-1, 0, 0]

  save_qpos: [False, True]
  max_ge_stage: 0

grasp_cfg:
  task_dict:
    f: [0, 0, 1]
    p: [0, 0, 0]
    t: [0, 0, 0]
    gamma: 180
  ge_param:
    type: 'qp'
    miu_coef: [0.1, 0]
    solver_type: 'batch_reluqp'
    k_lower: 0.2
    pressure_constraints:
      [ [[0, 1, 2, 3], 1.0], 
        [[0, 1, 2, 3, 4, 5, 6], 1.0],                       
        [[0], 0.3],                              
        [[1, 2, 3, 4, 5, 6], 0.8]                  
       ]                  # 可额外加入 ring finger distal

    enable_density: False
    solve_interval: 5

mogen_init: [0.4227, -1.5991, -1.8872, -3.0432, -0.9848,  3.2433,  0.1738, -0.2078, 0,0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,0]