##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

collision_spheres:
  base_link:
    - "center": [-0.01, -0.015, -0.075]
      "radius": 0.025
    - "center": [-0.01, -0.034, -0.054]
      "radius": 0.025
    - "center": [-0.01, 0.0, -0.049]
      "radius": 0.025
    - "center": [-0.01, -0.035, -0.016]
      "radius": 0.025
    - "center": [-0.01, 0.0, -0.017]
      "radius": 0.025
    - "center": [-0.01, 0.033, -0.019]
      "radius": 0.025
    - "center": [-0.01, 0.01, -0.075]
      "radius": 0.025
  link_1.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.015
    - "center": [0.0, 0.0, 0.049]
      "radius": 0.015
    - "center": [0.0, 0.0, 0.016]
      "radius": 0.015
    - "center": [0.0, 0.0, 0.033]
      "radius": 0.015
  link_2.0:
    - "center": [0.0, 0.0, 0.017]
      "radius": 0.015
    - "center": [0.0, 0.0, 0.032]
      "radius": 0.015
  link_3.0:
    - "center": [-0.003, 0.0, 0.009]
      "radius": 0.015
    - "center": [0.005, 0.01, 0.012]
      "radius": 0.005
    - "center": [0.005, -0.01, 0.012]
      "radius": 0.005
  link_3.0_tip:
    - "center": [0.0, 0.0, -0.001]
      "radius": 0.0125
  link_5.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.015
    - "center": [0.0, 0.0, 0.049]
      "radius": 0.015
    - "center": [0.0, 0.0, 0.016]
      "radius": 0.015
    - "center": [0.0, 0.0, 0.033]
      "radius": 0.015
  link_6.0:
    - "center": [0.0, 0.0, 0.017]
      "radius": 0.015
    - "center": [0.0, 0.0, 0.032]
      "radius": 0.015
  link_7.0:
    - "center": [-0.003, 0.0, 0.009]
      "radius": 0.015
    - "center": [0.005, 0.01, 0.012]
      "radius": 0.005
    - "center": [0.005, -0.01, 0.012]
      "radius": 0.005
  link_7.0_tip:
    - "center": [0.0, 0.0, -0.001]
      "radius": 0.0125
  link_9.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.015
    - "center": [0.0, 0.0, 0.049]
      "radius": 0.015
    - "center": [0.0, 0.0, 0.016]
      "radius": 0.015
    - "center": [0.0, 0.0, 0.033]
      "radius": 0.015
  link_10.0:
    - "center": [0.0, 0.0, 0.017]
      "radius": 0.015
    - "center": [0.0, 0.0, 0.032]
      "radius": 0.015
  link_11.0:
    - "center": [-0.003, 0.0, 0.009]
      "radius": 0.015
    - "center": [0.005, 0.01, 0.012]
      "radius": 0.005
    - "center": [0.005, -0.01, 0.012]
      "radius": 0.005
  link_11.0_tip:
    - "center": [0.0, 0.0, -0.001]
      "radius": 0.0125
  link_12.0:
    - "center": [-0.02, 0.0, 0.02]
      "radius": 0.03
  link_13.0:
    - "center": [0.0, 0.0, 0.01]
      "radius": 0.015
  link_14.0:
    - "center": [0.0, 0.0, 0.01]
      "radius": 0.015
    - "center": [0.0, 0.0, 0.03]
      "radius": 0.015
  link_15.0:
    - "center": [-0.002, 0.0, 0.0]
      "radius": 0.015
    - "center": [-0.002, 0.0, 0.014]
      "radius": 0.015
    - "center": [-0.002, 0.0, 0.025]
      "radius": 0.015
    - "center": [0.005, 0.01, 0.027]
      "radius": 0.005
    - "center": [0.005, -0.01, 0.027]
      "radius": 0.005
  link_15.0_tip:
    - "center": [0.0, 0.0, -0.001]
      "radius": 0.0125


